name: CI

on: [push, pull_request]

jobs:
  test:
    name: "${{matrix.os}} | Config: '${{matrix.config}}', Build options: '${{matrix.options.build}}'"
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022"]
        options:
          - { build: "", llvm: false }
          - { build: "-T ClangCL", llvm: true }

        config: ["Debug", "Release"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Install LLVM
        if: matrix.options.llvm == true
        uses: KyleMayes/install-llvm-action@v2.0.2
        with:
          version: "18.1.3"

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.config}} ${{matrix.options.build}}

      - name: Build
        run: cmake --build build --config ${{matrix.config}}

      - name: Run tests
        run: cmake --build build --config ${{matrix.config}} --target run-libnum-test
