name: CI

on: [push, pull_request]

jobs:
  test:
    name: "${{matrix.os}} | Config: '${{matrix.config}}', Options: '${{matrix.options}}'"
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022"]
        options: ["", "-T ClangCL"]
        config: ["Debug", "Release"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.config}} ${{matrix.options}}

      - name: Build
        run: cmake --build build --config ${{matrix.config}}

      - name: Run tests
        run: cmake --build build --config ${{matrix.config}} --target run-libnum-test
